name: Build and Push Podman Container to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Login to GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $CR_PAT | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Podman container
        run: |
          repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          owner=${{ github.actor }}  # use personal namespace
          podman build -t ghcr.io/$owner/$repo_name:latest ./website
      
      - name: Push container
        run: |
          repo_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          owner=${{ github.actor }}
          podman push ghcr.io/$owner/$repo_name:latest
